# Generated by Django 3.2.4 on 2021-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=14)),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('draft', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
