# Generated by Django 3.2.4 on 2021-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timeStamp',
        ),
    ]
