# Generated by Django 3.2.4 on 2021-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
