# Generated by Django 3.2.4 on 2021-07-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210726_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='confApt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_specialist', models.CharField(max_length=50)),
                ('apointment_date', models.DateField()),
                ('appointment_stime', models.DateTimeField()),
            ],
            options={
                'db_table': 'confApt',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='option',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
