# Generated by Django 3.2.4 on 2021-07-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20210726_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confapt',
            table=None,
        ),
    ]
