# Generated by Django 3.2.4 on 2021-07-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app1', '0011_alter_confapt_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='confApt1',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('required_specialist', models.CharField(max_length=50)),
                ('apointment_date', models.DateField()),
                ('appointment_stime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='confApt',
        ),
    ]
